export enum Emoji {
    pause = '⏸️',
    resume = '▶️',
    previous = '⏮️',
    skip = '⏭️',
    queue = '🎶',
    stop = '⏹️',
    shuffle = '🔀',
    loop = '🔁',
    Qfilters = '🎧',
    lyrics = '🎤',
    vote = '👍',
    invite = '🔗',
    support = '🆘',
    // Userinfo badges
    staff = '🛡️',
    partner = '🤝',
    BugHLevel1 = '🐛',
    BugHLevel2 = '🐛🐛',
    hypesquad = '🎉',
    HyperSquadBravery = '⚔️',
    HyperSquadBrilliance = '💡',
    HyperSquadBalance = '⚖️',
    Earlysup = '💎',
    Verifiedbot = '🤖',
    VerifiedDev = '👨‍💻',
    CertifiedMod = '👮',
    ActiveDev = '👨‍💻',
    online = '🟢',
    dnd = '🔴',
    idle = '🟠',
    invisible = '⚪',
    tick = '✔️',
    cross = '❌',
    home = '🏠',
    premium = '👑',
    steal = '⏳'
}